# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "OHBM BrainHack 2020"
email: ""
description: "OHBM Brainhack June 23-25th, 2020. Organized by the OHBM Open Science SIG."
baseurl: "/hackathon2020"
url: "https://ohbm.github.io/hackathon2020"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: ""

# Organizer Info
organizerName: "OHBM Open Science SIG"
organizerAlternateName: ""
organizerDescription: ""
organizerEmail: ""
organizerLogo: ""
organizerLink: ""

# Head
metaKeywords: "brainhack, montreal, neuroscience, AI"
twitterAccount: "@OhbmOpen"
socialImageSrcGooglePlus: ""
socialImageSrcTwitter: ""
socialImageSrcFacebook: ""

# Documents
c4pUrl: ""
c4sponsorsUrl: ""


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/#about", text: "About"}
 #- {permalink: "/speakers", text: "Speakers"}
 - {permalink: "/schedule", text: "Schedule"}
 - {permalink: "/logistics", text: "Logistics"}
 - {permalink: "/hackathon", text: "Hackathon"}
 - {permalink: "/team", text: "Team"}
bottomNavigationLinks:
# - {link: "https://docs.google.com/forms/d/e/1FAIpQLSdDHWdmixckSRi9LEvvIZHfzsoVbiwFbfHyOIms9DWZGMB7iQ/viewform?hl=en", text: "Join Brainhack Finland 2018"}
# - {link: "mailto:brainhackfinland@gmail.com", text: "Registrations are closed"}
# - {link: "https://twitter.com/abc_aalto/status/991572160169689088", text: "Recordings of the unconference talks"}
# - {link: "https://www.youtube.com/watch?v=ZsCGEQzLSbQ", text: "Recordings of the unconference talks"}
#rightNavigationButtons:
# - {link: "https://docs.google.com/forms/d/e/1FAIpQLSdDHWdmixckSRi9LEvvIZHfzsoVbiwFbfHyOIms9DWZGMB7iQ/viewform?hl=en", text: "Join Brainhack Finland 2018"}
# - {link: "mailto:brainhackfinland@gmail.com", text: "Registrations are closed"}
# - {link: "https://twitter.com/abc_aalto/status/991572160169689088", text: "Recordings of the unconference talks."}
# - {link: "https://www.youtube.com/watch?v=ZsCGEQzLSbQ", text: "Recordings of the unconference talks"}

# Hero Block
heroImage: "mtl_photo.jpg"
heroTitle: "OHBM Brainhack <typeout>"
eventDate: "23rd June 2020"
typeoutTextValues: '"June 23-25th, 2020", "Montreal, QC", ""'
typeoutFallback: ""
heroButtons:
# - {link: "https://docs.google.com/forms/d/e/1FAIpQLSdDHWdmixckSRi9LEvvIZHfzsoVbiwFbfHyOIms9DWZGMB7iQ/viewform?hl=en", text: "Join Brainhack Finland 2018"}
# - {link: "mailto:brainhackfinland@gmail.com", text: "Registrations are closed"}
# - {link: "https://twitter.com/abc_aalto/status/991572160169689088", text: "Recordings of the unconference talks."}
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSc8l68UAClcdXHwl27UuUI5yHHBDuu-LtUulFTuNKRL70j_mw/viewform", text: "Help us design the TrainTrack!"}

# About Block
aboutTitle: "About OHBM BrainHack 2020"
aboutBlock:
 - {title: "Share Ideas", image: "share.png", text: "Share your research and curiosity with other neuroimaging and computer science researchers."}
 - {title: "Build Projects", image: "code.png", text: "Try the presented tools on provided data or bring your own tools/data!" }
 - {title: "Be social", image: "community.png", text: "Brainhack Finland is a speed-dating event between neuroscientists and computer scientists in Finland." }
 - {title: "Learn Tools", image: "learn.png", text: "Learn about brain imaging data and how to apply the latest computational tools to your data." }

# Guests block
guestTitle: "Unconference talks"
guestBlock:
 - {title: "Riitta<br>Hari", image: "hari.jpg", text: "Prof. Em. Riitta Hari has pioneered the use of magnetoencephalography for studying sensory processing and motor control in healthy subjects and patient groups, with a main interest in the dynamics of human brain functions in naturalistic conditions. She will challenge our views during the unconference by sharing with us the unsolved questions of neuroscience."}
 - {title: "Lauri<br>Parkkonen", image: "parkkonen.jpg", text: "Prof. Lauri Parkkonen has been developing instrumentation and analysis tools for MEG since early 1990's and has an impressive knowledge of the most intricate MEG details. He will share his views on the current limitations of brain imaging methods and in which direction neuroimaging should be going next"}
 - {title: "Arto<br>Klami", image: "aklami.jpg", text: "Prof. Arto Klami is an expert on statistical machine learning and artificial intelligence. His main focus is in Bayesian modeling of complex data collections. He will talk about how well 'brain reading' works nowadays and what novel approaches could be used in studying the brain and its functions."}

# Guests2 block
guest2Title: "Ignite talks"
guest2Block:
 - {title: "Anna<br>Alexandrou", image: "alexandrou.jpg", text: ""}
 - {title: "Enrico<br>Glerean", image: "glerean.jpg", text: ""}
 - {title: "Mikko<br>Kivela", image: "kivela.jpg", text: ""}
 - {title: "Emilia<br>Oikarinen", image: "oikarinen.jpg", text: ""}
 - {title: "Juho<br>Piironen", image: "piironen.jpg", text: ""}
 - {title: "Kai<br>Puolamaki", image: "puolamaki.png", text: ""}
 - {title: "Marijn<br>van Vliet", image: "vliet.jpg", text: ""}
 - {title: "Alexander<br>Zhigalov", image: "zhigalov.jpg", text: ""}


# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Dept. of Neuroscience and Biomedical Engineering"
eventLocationLink: "http://nbe.aalto.fi/"
eventStreetAddress: "Rakentajanaukio 2"
eventAddressLocality: "Espoo"
eventAddressLocalityRegion: "Uusimaa"
eventPostalCode: "02150"
eventAddressCountry: "Finland"
eventStartTime: "2018-05-02T10:00"
eventDoorTime: "09:00"
eventEndTime: "2018-05-02T23:59"
eventPlaceCoordinates: "60.1877229, 24.8294535"
mapCenterCoordinates: "60.1877229, 24.8294535"
mapMobileCenterCoordinates: "60.1877229, 24.8294535"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Kinopalace Cinema"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
# - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=abc_aalto", icon: "twitter"}
# - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.brainhack.org/global2018", text: "Brainhack Global 2018"}
 -
  title: "Organizers and contacts"
  links:
   - {link: "https://twitter.com/eglerean", text: "Enrico Glerean (chair)"}
   - {link: "https://twitter.com/tijh", text: "Tommi Himberg"}
   - {link: "https://twitter.com/wmvanvliet", text: "Marijn van Vliet"}
   - {link: "https://twitter.com/abc_aalto", text: "Aalto Brain Centre (sponsor)"}
   - {link: "mailto:brainhackfinland@gmail.com", text: "brainhackfinland@gmail.com"}
 -
  title: "FAQ"
  links:
   - {link: "http://www.brainhack.org/global2018/codeofconduct.html", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Montreal"
directionDetailsCards:
 - {title: "From the Airport", information: 'The Pierre Elliot Trudeau (YUL) airport is about 30 minutes driving from the Old Port.'}
 - {title: "Public Transit", information: 'Google Transit is available in Montreal. Google maps is great for getting around, and the Transit app is handy for checking bus times if you choose to take public transportation. your way in Google Maps.'}
 - {title: "Lodging", information: 'For easy commuting to the Old Port, we recommend staying in an airbnb or hotel either in the Old Port, Griffintown, Downtown, or the Plateau.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Hackathon projects"
hackathonRows:
 - {title: "Multiplex networks", image: "muxnet.png", details: "Mikko's multiplex networks software is available at <a href=\"http://www.mkivela.com/pymnet/\">http://www.mkivela.com/pymnet/</a>. There are also some other software for analysing multiplex networks. For example <a href=\"http://muxviz.net\">http://muxviz.net</a> , <a href=\"https://graph-tool.skewed.de\">https://graph-tool.skewed.de</a>."}
 - {title: "SideR", image: "sideR.png", details: "<b>SideR</b> can be found here: <a href=\"http://www.iki.fi/kaip/sider.html\">http://www.iki.fi/kaip/sider.html</a>. Before coming to the hackathon, you need to have the following software installed before running sideR:<br>* R 3.4.0 or higher with the following packages which can be installed from CRAN (see https://www.r-bloggers.com/installing-r-packages/ for instructions): shiny, fastICA.<br>* A modern web browser such as Google Chrome.<br><br>We have tested sideR with a unix system (Mac OS X) but it should work in any system that has R with the above mentioned packages installed.<br><br>NB: R 3.4.0 includes somes substantial speedups to matrix computations which may affect the performance of the sideR. If you have an older version of R installed we therefore strongly recommended you to update to R 3.4.0 or newer!<br><br>An alternative to sideR is <br>tileR</b> which can be found here <a href=\"https://github.com/aheneliu/tiler\">https://github.com/aheneliu/tiler</a> along with installation instructions."}
 - {title: "Stan", image: "stan.png", details: "To run Stan you need to install R (see above) with packages <a href=\"https://CRAN.R-project.org/package=rstan\">rstan</a> and <a href=\"https://CRAN.R-project.org/package=rstanarm\">rstanarm</a>. The former has the functions that are needed to run arbitrary Stan programs, whereas the latter has precompiled Stan codes for some of the most common regression models (like linear regression, logistic regression etc.) with easy-to-use interface."}
 - {title: "Bring your own method/data", image: "whatever.png", details: "The three methods suggested above are just a starting point. If a group of participants wants to work on something else, this is of course possible. We have also prepare some data to use the methods above, but if you have your own data, please bring it with you and try to hack it with the methods presented."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
